### ISSUE TITLE
Doesn't seems to deploy anymore

### ISSUE THREAD

**Issue by bhack** [GeoNode/geonode-openshift#1]
This is the error i got running the script in openshift
remote:   Cloning git://github.com/GeoNode/geonode.git (to dev) to ./venv/src/geonode
remote:   Complete output from command /usr/bin/git submodule init -q:
remote:   
remote: ----------------------------------------
remote: Command /usr/bin/git submodule init -q failed with error code 128

**Comment by dvictori** [comment]
Does this geonode-openshift works? I'm looking for a place to host a geonode instance and Openshift seamed a good option (value wise - 3 gears for free)

**Comment by jj0hns0n** [comment]
doubt it works these days. PRs welcome.

**Comment by dvictori** [comment]
Hi Jeff, I'll give it a shoot, but I don't understand much about GeoNode
instalation from scratch (only used ubuntu packages), neither Openshift. So
not sure if I'll get too far.
